# Generated by Django 4.1.4 on 2022-12-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_ID', models.AutoField(primary_key=True, serialize=False)),
                ('song_Name', models.CharField(max_length=500)),
                ('singer_Name', models.CharField(max_length=500)),
                ('song_Genre', models.CharField(max_length=100)),
                ('song_Desc', models.CharField(max_length=100)),
                ('song_Image', models.ImageField(upload_to='images')),
                ('song_File', models.FileField(upload_to='Song')),
            ],
        ),
    ]
